### ISSUE TITLE
2 Difficulty options with no icons in the pregame menu

### ISSUE THREAD

**Issue by Pickleses** [GrahamMThomas/RoR2_Faster-Games#1]
https://cdn.discordapp.com/attachments/469263314954878978/665428521123971082/unknown.png

I'm not sure if this is intentional or not. I am also not sure if the mod is intended to be played on one of the two additional difficulties (not sure if there is a difference between the two) or on the game's default difficulties.

I really really enjoy the premise of this mod and if there's any way I can help feel free to contact me on discord: Pickleses#7594

**Comment by GrahamMThomas** [comment]
Hey! I'm really glad to hear you are enjoying the premise of the mod. 

With regards to the two difficulties. I have no idea why there is two. There is the one difficulty called faster that the mod is intended to use. I've tested the mod on 5 other PCs and none of the other ones manifested a second difficulty.

The difficulty not having an icon is purely a implementation issue. I wanted to make an icon but I haven't had the time / figured it out. If you want to make a PR with the logo as the difficulty icon that would be great. 

Another way you can help is play the mod with a different number of players to test the balance. I'm totally open to any feedback!

**Comment by Pickleses** [comment]
I think its some kind of problem with a different mod. Me and my friend use the same mods and he also has the problem. I'll do some testing and see if I can figure it out

**Comment by Andrej730** [comment]
Is it a bug that I mod difficulty has no icon?

**Comment by GrahamMThomas** [comment]
No it is not a bug. It is also in the TODO list in the readme.
