### ISSUE TITLE
Is mod based on Monsoon difficulty?

### ISSUE THREAD

**Issue by Andrej730** [GrahamMThomas/RoR2_Faster-Games#2]
Is mod difficulty based on Monsoon difficulty? By Monsoon difficulty I mean reduced health regeneration and ability to complete Monsoon challenges on "Faster" - obtain skins at Obelisk, complete Deicide challenge etc

**Comment by GrahamMThomas** [comment]
No. It's not a edited clone of Monsoon so you cannot complete challenges, neither do I think you should be able to.
