### ISSUE TITLE
Can you make various rates changeable via config?

### ISSUE THREAD

**Issue by AceKuper** [GrahamMThomas/RoR2_Faster-Games#4]
It's a pretty neat mod, but i would love if i could adjust various aspects of it via config it generates and do it separately for each one.

For example for me it feels that Difficulty scaling rises to quickly or i would just like only increase in base speed and spawn rate.

Is that possible to do? With vanilla values and your mod values mentioned in the description, so if i want to reset to them i could do it easily?

**Comment by GrahamMThomas** [comment]
Definitely planning on doing this soon. Will work on it hopefully soon

**Comment by GaloDoma** [comment]
Oh, agreed! This mod would be twice as kickass if we could just change the base move speed! Imagine a version of RoR2 where i can move and attack in unison without the need to sprint! Seems like a right fit for your mod! That said, maybe you could leave an option to have the game difficulty unaltered with your mod as well? I feel like the base game with altered base move speed could be quite intriguing too!

**Comment by GrahamMThomas** [comment]
Totally with you guys. I'm kind of trying to avoid my mod being a one stop shop for everything people want to tweak in game. But these few use cases make sense.

**Comment by GrahamMThomas** [comment]
Implemented config file! Fixed in #6f39a2922dbbcd0a8d3f0cde17f7d1617552b6f1
