### ISSUE TITLE
Broken in latest update

### ISSUE THREAD

**Issue by scottcollado** [GrahamMThomas/RoR2_Faster-Games#7]

**Comment by scottcollado** [comment]
Characters never spawn into the game after the Survivor of the Void Expansion

**Comment by GrahamMThomas** [comment]
Awese, thanks for the update. I'll take a look soon!

**Comment by ihateyou666** [comment]
I guess this mod became dead

**Comment by GrahamMThomas** [comment]
Yeah I haven't been playing recently and haven't updated. I'll get to it eventually but don't have a timeline currently.

**Comment by GrahamMThomas** [comment]
Finally got around to updating the game. Now works on current version. Closing
